from tkinter import *
import math
class MyWindow:
    def __init__(self, win):
        self.lbl1=Label(win, text='X')
        self.lbl2=Label(win, text='Y')
        self.lbl5=Label(win, text='Z')
        self.lbl3=Label(win, text='Result:')
        self.lbl4=Label(win, text='Logarithm Calculator by 2k5master')
        self.lbl6=Label(win, text='Y is the base!')
        self.t1=Entry()
        self.t2=Entry()
        self.t4=Entry()
        self.t3=Entry()
        self.lbl1.place(x=0, y=33)
        self.t1.place(x=50, y=33)
        self.lbl2.place(x=0, y=66)
        self.t2.place(x=50, y=66)
        self.lbl4.place(x=0, y=0)
        self.t4.place(x=50, y=100)
        self.lbl5.place(x=0, y=100)
        self.lbl6.place(x=250, y=150)
        self.b1=Button(win, text='Logarithm (Base)', command=self.logbase)
        self.b2=Button(win, text='Logarithm (E)', command=self.loge)
        self.b3=Button(win, text='Logarithm (Base10)', command=self.log10)
        self.b1.place(x=250, y=30)
        self.b2.place(x=250, y=63)
        self.b3.place(x=250, y=97)
        self.lbl3.place(x=0, y=150)
        self.t3.place(x=50, y=150)
    def logbase(self):
        self.t3.delete(0, 'end')
        x=int(self.t1.get())
        y=int(self.t2.get())
        result=math.log(x, y)
        self.t3.insert(END, str(result))
    def loge(self):
        self.t3.delete(0, 'end')
        x=int(self.t1.get())
        result=math.log(x)
        self.t3.insert(END, str(result))
    def log10(self):
        self.t3.delete(0, 'end')
        x=int(self.t1.get())
        result=math.log(x, 10)
        self.t3.insert(END, str(result))

window=Tk()
mywin=MyWindow(window)
window.title('Logarithm Calculator')
window.geometry("380x180+10+10")
window.mainloop()
